package com.minionslab.core.domain.enums;

public enum MinionType {
  WORKFLOW_MANAGER,
  COMMUNICATION_AGENT,
  SECURITY_MONITOR,
  RESOURCE_MANAGER,
  USER_SUPPORT,
  AUTOMATION_ENGINEER,
  INTEGRATION_AGENT,
  TESTING_AGENT,
  LOGGING_AGENT,
  USER_DEFINED_AGENT,
  CHAT,
  ASSISTANT,
  AGENT;
}
